// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABcCKWyFmUsUfAvSW95Cag1pEITL5WQCY',
    appId: '1:955973288799:web:80e6a4cd8ce69b3554ecea',
    messagingSenderId: '955973288799',
    projectId: 'dev-da-app',
    authDomain: 'dev-da-app.firebaseapp.com',
    storageBucket: 'dev-da-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj_wu5DScoi561fuTnmLmXnGJzW3PrsVk',
    appId: '1:955973288799:android:b45ead7987f0fc7554ecea',
    messagingSenderId: '955973288799',
    projectId: 'dev-da-app',
    storageBucket: 'dev-da-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApEgUwtkDxLnK2FJ_EDy7x5l7x8obZYdA',
    appId: '1:955973288799:ios:7b889bc4ab7726cb54ecea',
    messagingSenderId: '955973288799',
    projectId: 'dev-da-app',
    storageBucket: 'dev-da-app.firebasestorage.app',
    iosBundleId: 'chi.devdavinchi.firstFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApEgUwtkDxLnK2FJ_EDy7x5l7x8obZYdA',
    appId: '1:955973288799:ios:7b889bc4ab7726cb54ecea',
    messagingSenderId: '955973288799',
    projectId: 'dev-da-app',
    storageBucket: 'dev-da-app.firebasestorage.app',
    iosBundleId: 'chi.devdavinchi.firstFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABcCKWyFmUsUfAvSW95Cag1pEITL5WQCY',
    appId: '1:955973288799:web:83958c00970f451754ecea',
    messagingSenderId: '955973288799',
    projectId: 'dev-da-app',
    authDomain: 'dev-da-app.firebaseapp.com',
    storageBucket: 'dev-da-app.firebasestorage.app',
  );
}
